- name: Professional AWS CLI Installation (Darwin)
  hosts: localhost
  tasks:
    - name: Ensure Homebrew AWS CLI is completely eradicated
      homebrew:
        name: awscli
        state: absent

    - name: Download official statically linked AWS standalone package
      get_url:
        url: 'https://awscli.amazonaws.com/AWSCLIV2.pkg'
        dest: '/tmp/AWSCLIV2.pkg'

    - name: Install the package headlessly
      become: yes
      command: installer -pkg /tmp/AWSCLIV2.pkg -target /
      args:
        creates: /usr/local/bin/aws
